name: create dev build

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

env:
  PACKAGES: make zip unzip wget

jobs:
  build:
    name: Create dev DCS Mod package
    runs-on: ubuntu-latest
    steps:
    - name: Install Packages
      run: sudo apt-get install $PACKAGES

    - name: Checkout Code
      uses: actions/checkout@v2

    - id: trim_ref
      run: echo "VERSION=${{ github.sha }}" >> $GITHUB_ENV

    - name: Build Mod
      run: make build

    # GitHub will zip whatever we give it, even if it's already a zip,
    # so we unzip the build and upload its contents to avoid double-zipping
    - name: Unzip Data
      run: unzip DCT-${{ env.VERSION }}.zip -d build

    - name: Upload Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: DCT-${{ env.VERSION }}
        path: build/
        retention-days: 14
